### ISSUE TITLE
basic question: how does idba_ud treat even k-mer sizes (or palindromic kmers)?

### ISSUE THREAD

**Issue by jvollme** [loneknightpy/idba#14]
Hi, this is just a basic question for understanding how IDBA-UD works in comparison to other assemblers.
Almost all de bruijn graph assemblers specifically forbid even kmer lengths to avoid palindromic kmers. However, i can run IDBA_UD with even or uneven k-mer lengths and the default values seem to be even.  
How come that IDBA-UD does not seem to have any issue with even or palindromic kmers?

**Comment by loneknightpy** [comment]
@jvollme It handles even k-mer elegantly. Basically, palindromic k-mers are treated as normal k-mers except that they can be traveled from both directions. Palindromic k-mer do introduce some branches in the graph, but they usually can be resolved while iterating k-mer to maxk. Actually, palindromic k-mers are very rare when k is big. (e.g. 100)

**Comment by jvollme** [comment]
OK. thanks for the info
