### ISSUE TITLE
How to Install????????

### ISSUE THREAD

**Issue by cement-head** [loneknightpy/idba#37]
I do not understand how to install this software.

After the ./build script executes, then what should I do?

**Comment by cement-head** [comment]
Wait a sec, after ./build.sh completes, does one simply run each executable from within the bin directory from CLI?

**Comment by Stefano04** [comment]
I launched as written

.configure
make

Everything works then calling the executables

**Comment by cement-head** [comment]
Yeah, thanks - I figured that out.
