### ISSUE TITLE
logic_error: ShortSequence: Sequence is too long.

### ISSUE THREAD

**Issue by ReneKat** [loneknightpy/idba#52]
Hello,
I am new to IDBA and the genomics world, so I am hoping to get some help to resolve this error. 
My command is:
`idba_ud -r db.fa.gz -o /Results/`
After a split second I get the following logic error:
terminate called after throwing an instance of 'std::logic_error'
  what():  ShortSequence: Sequence is too long.

My sequencing reads are in an interleaved gzipped fasta file; between 100-200bp. In the manual, it is written that the -r accepts fasta read file (<=600). I'm assuming this is 600bp? So, I'm unsure how my reads are too long. 

Thanks for any guidance!

**Comment by jvollme** [comment]
Hi renekat, I'm not sure IDBA can handle gzip compressed files. Maybe that's the problem? Try decompressing your input file with "gunzip db.fa.gz" and then running idba again with "-r db.fa"

**Comment by ReneKat** [comment]
Hi jvollme,
That was exactly the problem. Thanks so much for your quick reply!
