### ISSUE TITLE
Detailed Docs?

### ISSUE THREAD

**Issue by sklages** [loneknightpy/idba#8]
Hi,

is there any documentation available apart from <idba_hyb/ud> without parameters?
E.g. how do the '--read_level_n' parameter work? If i had two MP lib, I'd use '--read_level_2' for the first and '--read_level_3' for the second lib? Is the MP insert size relevant for these parameters?

The command output in general is really minimal; a more detailed description of the parameters would be really great. 

best,
Sven

**Comment by jvollme** [comment]
Just to keep this question in discussion:
 Concerning the read_levels: Based on the principle of other assemblers such as SOAP, I would **assume** that it's usually best to sort different libraries by insert size and to use the smalles insert size first for intital scaffolding. And then to add the next highest insert-size library for scaffolding the initial scaffolds, and so on...
Therefore you would add the smallest insert size library as "-r", the second-smallest as "--read_level2" and so on (**I assume**). Mate-pairs would therefore be added as one of the highest read-levels (**again I assume**).
IDBA_UD seems to support upto 5 different library "channels" so if you would have more than that it would **probably** make sense to merge datasets from libraries which share a similar insert size.

Are these assumptions correct?

**Comment by loneknightpy** [comment]
@jvollme You are right. The read libraries are applied sequentially, read, --read_level2, etc.
