### ISSUE TITLE
idba_hybrid : Segmentation fault (kMaxShortSequence=256)

### ISSUE THREAD

**Issue by sklages** [loneknightpy/idba#9]
Dear Yu Peng,

I tried to use idba_hybrid to assemble illumina PE/MP read data (genomic) using abyss-assembly-scaffolds generated with this dataset.
In one approach I used the MP data for scaffolding (read_level_n), in another I used the MP data together with the PE data as normal reads (-r).

```
reads 1
long reads 0
extra reads 0
read_length 83
aligned 0 reads
distance mean -nan sd -nan
confirmed bases: 0
reference contigs: 1 n50: 0 max: 0 mean: 0 total length: 0 n80: 0
invalid insert distance
kmer 41
kmers 26 26
merge bubble 0
contigs: 1 n50: 66 max: 66 mean: 66 total length: 66 n80: 66
aligned 0 reads
distance mean -nan sd -nan
invalid insert distance

[more kmers]
```

Both died with a Segmentation fault on high memory machines (1TiB RAM)...  without further error message or any hint what was going wrong. A program shouldn't segfault ..

What more info can I provide? Any idea?

best,
Sven

**Comment by loneknightpy** [comment]
It seems the input has only one read with length 83. Are you sure you use the right input file?

**Comment by sklages** [comment]
No :-)
I erroneously used a "file-of-filenames" as input as I have more than one file to be assembled. Concatenating all input files into one huge file should solve the problem.
